version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: comments_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
        - ./frontend/dist:/app/frontend/dist
        - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: celery-worker
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
      - ./media:/app/media 
    depends_on:
      - web
      - redis

volumes:
  mysql_data:
